//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderdetail
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public int pid { get; set; }
        public int qty { get; set; }
        public double price { get; set; }
        public double Bill { get; set; }
    
        public virtual ordermain ordermain { get; set; }
        public virtual Product Product { get; set; }
    }
}
